### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by JayantDevkar** [WebDevSimplified/Markdown-Blog#1]
So I was watching your videos to make my own dynamic website, but I ran into a problem.
Here is the error:
Error: Failed to lookup view "index" in views directory "C:\Users\jayan\Side_project code\Mustang_Connect\views"
    at Function.render (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\response.js:1012:7)
    at C:\Users\jayan\Side_project code\Mustang_Connect\server.js:10:9    at Layer.handle [as handle_request] (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\layer.js:95:5)    
    at next (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\layer.js:95:5)    
    at C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\jayan\Side_project code\Mustang_Connect\node_modules\express\lib\router\index.js:275:10)

**Comment by ghost** [comment]
Make sure that your view files are located in '/views/articles' folder, and the paths in the router are all correct. The script can't just find the index.ejs file. (yes, make sure your view files have .ejs extension)

**Comment by Simqles** [comment]
I get this error
`ReferenceError: C:\Users\User\Desktop\SimqleApp\SimqleApp2\views\articles\show.ejs:123
    121|         <div class="container-fluid bg-dark text-white" style="margin-top: 2%;">

    122|           

 >> 123|           <h1 class="mb-1 text-center"><%= article.title %> </h1>

    124|         </div>

    125|       <div class="container-fluid blog-footer">

    126|         <p>Simqle Team |  Bütün Hakları Saklıdır | <a href="https://simqles.github.io/">Hakkımızda </a><b> | </b><a href="https://simqles.github.io">Nedim Talha</a>.</p>


article is not defined
    at eval (eval at compile (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\ejs\lib\ejs.js:662:12), <anonymous>:12:26)
    at show (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\ejs\lib\ejs.js:692:17)
    at tryHandleCache (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\ejs\lib\ejs.js:272:36)
    at View.exports.renderFile [as engine] (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\User\Desktop\SimqleApp\SimqleApp2\node_modules\express\lib\response.js:1012:7)
    at C:\Users\User\Desktop\SimqleApp\SimqleApp2\routes\article.js:11:9
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`
this is my code
`const express = require('express');
const router = express.Router();
const Article = require('../models/article');

router.get('/new', (req, res) => {
    res.render('articles/new', { article: new Article() })
})
router.get('/:id', async(req, res) => {
    const article = await Article.findById(req.params.id)
    if(article == null) res.redirect('/')
    res.render('articles/show')
})
router.post('/', async(req, res) => {
    var article = new Article({
        title: req.body.title,
        description: req.body.description,
        markdown: req.body.markdown
    })

    try {
       article = await article.save()
       res.redirect(`/articles/${article.id}`)
    } catch(err) {
        console.log(err)
        res.render('articles/new', { article: article })
    }
})
module.exports = router`
this is my ejs code 
`        <div class="container-fluid bg-dark text-white" style="margin-top: 2%;">
          
          <h1 class="mb-1 text-center"><%= article.title %> </h1>
        </div>
      <div class="container-fluid blog-footer">
        <p>Simqle Team |  Bütün Hakları Saklıdır | <a href="https://simqles.github.io/">Hakkımızda </a><b> | </b><a href="https://simqles.github.io">Nedim Talha</a>.</p>
        <p>
          <a href="#">Başa dön</a>
        </p>

    </div>`

**Comment by igorcafe** [comment]
Are you using a `src/` folder or any different structure?
If so, try adding:
```js
app.set('views', 'src/views')
```
